---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi
  template:
    metadata:
      labels:
        app: medi
    spec:
      containers:
        - name: medicure
          image: muzammilp/medicureimgk8s8082:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
          
---
apiVersion: v1
kind: Service
metadata:
  name: medi
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30331
  selector:
    app: medi
