---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi
  template:
    metadata:
      labels:
        app: medi
    spec:
      containers:
        - name: medicure
          image: muzammilp/insuranceimgaddbook:latest
          ports:
            - containerPort: 8086
          env:
            - name: PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: medi
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: medi
